M48
; DRILL file {KiCad 9.0.6} date 2025-11-21T09:32:43+0100
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2025-11-21T09:32:43+01:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.6
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C3.200
%
G90
G05
T1
X102.0Y-39.0
X102.0Y-173.0
X144.0Y-39.0
X144.0Y-173.0
M30
