M48
; DRILL file {KiCad 9.0.5} date 2025-12-11T12:13:36+0100
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2025-12-11T12:13:36+01:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.5
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C3.200
%
G90
G05
T1
X102.0Y-39.0
X102.0Y-173.0
X144.0Y-39.0
X144.0Y-173.0
M30
